AUTHENTICATION_TYPE: "Database"
FEATURE_GITHUB_LOGIN: false
FEATURE_DIRECT_LOGIN: false

FEATURE_BUILD_SUPPORT: true

FEATURE_GITHUB_BUILD: true
GITHUB_TRIGGER_CONFIG:
  CLIENT_SECRET: "8bd923a5768a59f2e5f848752fa71ae62f4991ce"
  GITHUB_ENDPOINT: "https://www.google.com"
  CLIENT_ID: "fc0ef3cf19f90de48af9"

FEATURE_BITBUCKET_BUILD: true
BITBUCKET_TRIGGER_CONFIG:
  CONSUMER_KEY: A39bvHgf3ZJxdvAXyS
  CONSUMER_SECRET: VtqYfxbjDNFUsYbsU3vcTTqbyGxbGvYf

BRANDING:
  logo: "y"
  footer_img: "u"
  footer_url: "u"

DB_URI: mysql://sql9351936:kBCXc7eizT@sql9.freesqldatabase.com:3306/sql9351936
DOCUMENTATION_ROOT: "/documentation"
CONTACT_INFO:
  - "mailto:jonathankingfc@gmail.com"
LOGS_MODEL: "elasticsearch"
LOGS_MODEL_CONFIG:
  elasticsearch_config:
    access_key: elastic
    secret_key: nf567zCQgIVMrDvDGIpIHScG
    host: bfd70499058e4485854f8bacf06af627.us-central1.gcp.cloud.es.io
    port: 9243

FEATURE_GITLAB_BUILD: true
GITLAB_TRIGGER_CONFIG:
  CLIENT_ID: 304c96b0015a469f6cdc907a22acbc5692d8ac2958b19a19a2585811e0c1019f
  CLIENT_SECRET: 45060b331c39c30bd532eb71c720739d177f1a22238da470eab6a5e19f26057a
  GITLAB_ENDPOINT: "https://google.com"

FEATURE_GOOGLE_LOGIN: true
GOOGLE_LOGIN_CONFIG:
  CLIENT_SECRET: 0mQogdczWFnNemnVp5esDuas
  CLIENT_ID: 511815388398-ng379ngbt3ivpno3all76540eh11ebu7.apps.googleusercontent.com

FEATURE_ACTION_LOG_ROTATION: true
ACTION_LOG_ARCHIVE_PATH: "path/to/path"
ACTION_LOG_ARCHIVE_LOCATION: "hey"
DISTRIBUTED_STORAGE_CONFIG:
  storage_one:
    - ello
  hey:
    - woah

FEATURE_SECURITY_SCANNER: true
SECURITY_SCANNER_ENDPOINT: htp://google.com
SECURITY_SCANNER_V4_ENDPOINT: https://asfaasdfdssd.com/
