SERVER_HOSTNAME: quay:8081
FEATURE_ACTION_LOG_ROTATION: true
PREFERRED_URL_SCHEME: http
ACTION_LOG_ARCHIVE_PATH: "path/to/archive"
ACTION_LOG_ARCHIVE_LOCATION: "us_s3"
FEATURE_SECURITY_SCANNER: true
FEATURE_SECURITY_NOTIFICATIONS: false
SECURITY_SCANNER_ENDPOINT: "localhost:8080"
DISTRIBUTED_STORAGE_CONFIG:
  test_location: ["Test_Location", "Fuck"]
TEAM_RESYNC_STALE_TIME: 5da
