basePath: /api/v1
host: localhost:8080
info:
  contact:
    email: joking@redhat.com
    name: Jonathan King
  license: {}
  title: Config Tool Editor API
  version: "0.0"
paths:
  /api/v1/config:
    get:
      description: This endpoint will load the config bundle mounted by the config-tool into memory. This state can then be modified, validated, downloaded, and optionally committed to a Quay operator instance.
      produces:
      - application/json
      responses: {}
      summary: Load the mounted config bundle into local state
swagger: "2.0"
